# Generated by Django 4.1.4 on 2023-01-21 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startme', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='desc',
            field=models.CharField(default='Enter descp', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(default='Enter User Name', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_img',
            field=models.ImageField(blank=True, default='media/default.jpg', null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='title',
            field=models.CharField(default='Title of the project', max_length=200, null=True),
        ),
    ]
