# Generated by Django 4.1.4 on 2023-01-24 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startme', '0003_profile_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='instagram',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='images',
            field=models.ImageField(default='media/default.jpg', upload_to='media'),
        ),
    ]
