# Generated by Django 4.1.4 on 2023-01-26 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startme', '0004_profile_instagram_alter_profile_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='projectcomplete',
            field=models.CharField(default='', max_length=3, null=True),
        ),
    ]
