# Generated by Django 4.1.4 on 2023-01-26 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startme', '0005_profile_projectcomplete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='projectcomplete',
            field=models.CharField(default='Enter in numbers', max_length=3, null=True),
        ),
    ]
