# Generated by Django 4.1.4 on 2023-01-26 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startme', '0006_alter_profile_projectcomplete'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='experience',
            field=models.CharField(default='None', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='reviews',
            field=models.CharField(default='None', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='totalclients',
            field=models.CharField(default='None', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='projectcomplete',
            field=models.CharField(default='None', max_length=3, null=True),
        ),
    ]
