# Generated by Django 4.1.4 on 2023-01-26 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startme', '0007_profile_experience_profile_reviews_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(default='{{user.profile.name}}', max_length=200, null=True),
        ),
    ]
