# Generated by Django 4.1.4 on 2023-01-26 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startme', '0008_alter_profile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(default='Enter Your Name', max_length=200, null=True),
        ),
    ]
