# Generated by Django 4.1.4 on 2023-01-26 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startme', '0009_alter_profile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='projectcomplete',
            field=models.CharField(default='projectcomplete_text', max_length=3, null=True),
        ),
    ]
