# Generated by Django 4.1.4 on 2023-01-26 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startme', '0010_alter_profile_projectcomplete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='projectcomplete',
            field=models.CharField(default='None', max_length=3, null=True),
        ),
    ]
