# Generated by Django 4.1.4 on 2023-01-26 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startme', '0014_alter_profile_totalclients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='instagram',
            field=models.URLField(default='instagram_text', null=True),
        ),
    ]
