# Generated by Django 4.1.4 on 2024-10-17 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startme', '0016_alter_profile_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='desc',
            field=models.CharField(choices=[('web_dev', 'Full Stack Web Development'), ('graphic_design', 'Graphic Design'), ('content_writing', 'Content Writing'), ('seo_specialist', 'SEO Specialist'), ('data_analysis', 'Data Analysis'), ('mobile_dev', 'Mobile App Development'), ('digital_marketing', 'Digital Marketing'), ('cloud_computing', 'Cloud Computing'), ('cyber_security', 'Cyber Security'), ('ui_ux_design', 'UI/UX Design')], default='web_dev', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='instagram',
            field=models.URLField(default='https://www.instagram.com', null=True),
        ),
    ]
